# Generated by Django 6.0.1 on 2026-01-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mashina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('yil', models.IntegerField()),
                ('narx', models.DecimalField(decimal_places=2, max_digits=12)),
                ('probeg', models.IntegerField()),
                ('ahvol', models.CharField(choices=[('YANGI', 'Yangi'), ('ISHLATILGAN', 'Ishlatilgan')], max_length=15)),
                ('rang', models.CharField(max_length=30)),
                ('viloyat', models.CharField(max_length=50)),
                ('tavsif', models.TextField()),
                ('holat', models.CharField(choices=[('KUTILMOQDA', "To'lov kutilmoqda"), ('FAOL', 'Faol'), ('SOTILGAN', 'Sotilgan'), ('OCHIRILGAN', "O'chirilgan")], default='KUTILMOQDA', max_length=15)),
                ('korilganlar', models.IntegerField(default=0)),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-yaratilgan'],
            },
        ),
        migrations.CreateModel(
            name='MashinaRasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='mashina_rasmlar/')),
                ('asosiy', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sevimli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
