# Generated by Django 6.0.1 on 2026-01-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tavsif', models.TextField()),
                ('faol', models.BooleanField(default=True)),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('holat', models.CharField(choices=[('KUTILMOQDA', 'Kutilmoqda'), ('TOLANDI', "To'landi"), ('BEKOR', 'Bekor')], default='KUTILMOQDA', max_length=15)),
                ('click_trans_id', models.CharField(blank=True, max_length=255, null=True)),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-yaratilgan'],
            },
        ),
    ]
