# Generated by Django 6.0.1 on 2026-01-10 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0002_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tolov',
            name='foydalanuvchi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tolov',
            name='mashina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.mashina'),
        ),
        migrations.AddField(
            model_name='tolov',
            name='paket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paket'),
        ),
    ]
